#! /bin/sh

picom -f &
pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output HDMI-2 --mode 1920x1080 --rate 60 &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

nitrogen --restore &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh
